# Generated by Django 5.1.1 on 2024-09-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employeemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='phone_number',
            field=models.IntegerField(max_length=15),
        ),
    ]
