# Generated by Django 5.1.1 on 2024-09-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeemodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
